stages:
  - publish
  - deploy

variables:
  IMAGE_NAME: $GITLAB_USER_LOGIN/soilartificialization:latest
  # | tr '[:upper:]' '[:lower:]' .

publish:
  image: docker
  stage: publish
  services:
    - docker:dind
  only:
    - production
  environment: production
  before_script:
    - echo $PAT | docker login $CI_REGISTRY -u "$GITLAB_USER_LOGIN" --password-stdin
  script:
    - docker build --tag $CI_REGISTRY/$IMAGE_NAME .
    - docker push $CI_REGISTRY/$IMAGE_NAME

deploy:
  image: docker
  stage: deploy
  services:
    - docker:dind
  only:
    - production
  environment: production
  before_script:
    - mkdir -p ~/.ssh
    # cat ~/.ssh/privkey | base64 -w0 > privKey.base64
    - echo "$SSH_PRIV_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - which ssh-agent || (apk add openssh-client)
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - scp -rp ./docker-compose.prod.yml $SSH_USER@$SSH_HOST:$WORK_DIR
    # TODO test & add a filter on docker builder prune like docker builder prune --filter="label=name=soilartificialization"
    - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && mkdir -p ./renv/.cache && docker compose -f docker-compose.prod.yml down && docker rm soilartificialization-app-1 && docker rmi soilartificialization-app && docker rmi soilartificialization && docker builder prune -a && docker compose -f docker-compose.prod.yml up -d && exit"
  after_script:
    - rm -rf ~/.ssh
