# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - publish
  - deploy

variables:
  IMAGE_NAME: $GITLAB_USER_LOGIN/$CI_PROJECT_NAME:latest

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

publish:
  image: docker
  stage: publish
  services:
    - docker:dind
  only:
    - production
  environment: production
  before_script:
    - echo $PAT | docker login $CI_REGISTRY -u "$GITLAB_USER_LOGIN" --password-stdin
  script:
    - docker build --tag $CI_REGISTRY/$IMAGE_NAME .
    - docker push $CI_REGISTRY/$IMAGE_NAME

deploy:
  image: docker
  stage: deploy
  services:
    - docker:dind
  only:
    - production
  environment: production
  before_script:
    - mkdir -p ~/.ssh
    # cat ~/.ssh/privkey | base64 -w0 > privKey.base64
    - echo "$SSH_PRIV_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - which ssh-agent || (apk add openssh-client)
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - scp -rp ./docker-compose.prod.yml $SSH_USER@$SSH_HOST:$WORK_DIR
    - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && docker compose -f docker-compose.prod.yml up -d && exit"
  after_script:
    - rm -rf ~/.ssh
